sudo: required
language: c
cache: ccache
env: GCC_VERSION=5
addons: &gcc5
  apt: 
    packages: 
      - g++-5 
      - gcc-5 
  sources: 
    - sourceline: 'ppa:ubuntu-toolchain-r/test'
script:
#
# Travis CI Script by Caio Oliveira aka Caio99BR <caiooliveirafarias0@gmail.com>
#

# Install dependency
#- sudo add-apt-repository ppa:ubuntu-toolchain-r/test
#- sudo apt-get update
#- sudo apt install 
# getting UberTC
- git clone  --depth=1 "https://bitbucket.org/matthewdalex/arm-eabi-5.x" "../arm-eabi-5.x"

#
# This will call build.sh with following parameters inside ${nbasebuildsh}:
#
# 'export ndevicechoice="#"'
# 'export nbasebuildsh="${ndevice}${ndevicechoice}${ntoolchain}${nbuild}q""'
# 'source build.sh <<< "${nbasebuildsh}"'
# 'export zipfile#="${zipfile}"'
#
# ${nclean} = Clean zip "1" and "2" is "Clean Kernel" 
- nclean="12"
# "o" is to disable/enable output when building kernel
- noutput="o"
# "3" is "Device Choice"
- ndevice="1"
# ${ntoolchain} = "4" is "Toolchain Choice"
- ntoolchain="47"
- export CROSS_COMPILE="$(pwd)/../arm-eabi-5.x/bin/arm-eabi-"
# ${nbuild} = "5" is "Build Kernel" and "6" is "Zip the kernel and Modules"
- nbuild="56"
# ${nimage} = "7" is "Compressed image on/off"
#- nimage="7"
# Last "q" is to Exit of Script
# ${ndevicechoice} is "Number of Choice under Device Choice"
- ndevicechoice="1"
- export nbasebuildsh="${nclean}${ntoolchain}${ndevice}${ndevicechoice}${nimage}${nbuild}q"
- find / -name the_name_of_the_file.so
- echo $LD_LIBRARY_PATH
#- source build.sh <<< "${nbasebuildsh}"
- export ARCH=arm && export SUBARCH=arm
- make clean && make mrproper CFLAGS='-march=armv7-a -mtune=cortex-a8 -mfpu=neon'
- make ancora_oc_exuv_defconfig CFLAGS='-march=armv7-a -mtune=cortex-a8 -mfpu=neon'
- make -j$(nproc –all) CFLAGS='-march=armv7-a -mtune=cortex-a8 -mfpu=neon'


# Export of zipfile to deploy
#- export zipfile="${zipfile}"

deploy:
  provider: releases
  skip_cleanup: true
  api_key: "ed6c74b60bc30491782f16bd90dd604d42150da1"
  file: "arch/${ARCH}/boot/Image*"
  on:
    tags: true

